### ISSUE TITLE
nutcracker-cli relies on deprecated api in codegangsta/cli

### ISSUE THREAD

**Issue by mcgin** [nutmegdevelopment/nutcracker-cli#1]
`DEPRECATED Action signature.  Must be`cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature`

**Comment by nm-harry** [comment]
This is resolved by 13897ed
